### ISSUE TITLE
 Can't resolve 'crypto'

### ISSUE THREAD

**Issue by MaxiSanchezR** [aldabil21/react-scheduler#10]
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

FOR WEBPACK V5

**Comment by aldabil21** [comment]
Hi @MaxiSanchezR 

I haven't face any errors regarding this, however `crypto` can be thrown away, since it's used just to generate random id's for local use-case, which is most likely not needed, data should be saved in remote storage.
If you would like, you cant delete it and replace the `randomBytes` with `Math.random` maybe. If you PR this, would appreciate it :)

**Comment by tommy-yoon** [comment]
I am using webpack 5.x and had the same issue.
I found a workaround in https://stackoverflow.com/a/67076572/3800091

**Comment by alexandergurkovdev** [comment]
I use create-react-app and craco plugin. I customize webpack configuration and problem solved.

`const CracoAlias = require('craco-alias');

module.exports = {
  webpack: {
    configure: (webpackConfig, { env, paths }) => {
      webpackConfig.resolve.fallback = {
        crypto: false,
      };
      return webpackConfig;
    },
  },
};`

**Comment by aldabil21** [comment]
no mpre in 2.1.1
