### ISSUE TITLE
Load events with react query

### ISSUE THREAD

**Issue by naor10** [aldabil21/react-scheduler#123]
Hi,

I'm using react query and I want to pass the events through the state by the events prop, after fetching and setting the new state.
It seems that the calendar keeps the initial empty array state instead of updating with the new events from the state.

Appreciate any help.

**Comment by aldabil21** [comment]
yes this is intentional.
To update the events you can:
1. use `getRemoteEvents` to get remote events.
2. use `useScheduler` hook to progmatically update state, there is `setEvents` function.

Let me know if this solves your issue.

Also you could look into: https://github.com/aldabil21/react-scheduler/issues/39

**Comment by naor10** [comment]
I solved the issue like that:

```
const queryClient = useQueryClient();

const fetchRemote = async (query) => {
    const data = await queryClient.fetchQuery("events", getEvents)
    return data;
  };

  // ...

  return (
    <div>
      <Scheduler
         // ...
        remoteEvents={fetchRemote}
      />
    </div>
  );
```

Before I tried to use `useQuery` hook, which probably requires me to use `setEvents` function in `useScheduler` hook.

I prefer the first choice.

**Comment by aldabil21** [comment]
Cool. All roads lead to rome
