### ISSUE TITLE
Possible to have a custom render of multi-day events in calendar header?

### ISSUE THREAD

**Issue by firstpersoncode** [aldabil21/react-scheduler#128]
I'm using the react-schedule library in my project and I was wondering if there is already a feature for custom rendering of multi-day events in the calendar header. These events are rendered there because their start and end dates span more than one day.

In day view, the event will be rendered there if it spans until the next day, and in week view, the event will be rendered there if it spans until the next week.

If there is a way to achieve this through existing customization options, I would appreciate guidance on how to do so.

Thank you for your time and for maintaining this library!

**Comment by firstpersoncode** [comment]
And it seems like we cannot customize the events rendered in "month" view.

The reason I need to customize all the events rendered (including events that being rendered in the calendar header) in all views is because I need to have custom on click event on every events.

**Comment by aldabil21** [comment]
You are right, and thats intentional.
the multi-day events, and month events, both have a very limit space, and didn't find a way to make customizable, since doing so, may break the width/height of the event, which can result in showing wrong time-slot of the event.

I will keep this open to until I re-think it
