### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by naor10** [aldabil21/react-scheduler#186]
Hi,
In case I have ~200 events, the calendar renders in about 10 seconds in month view.

Could it be improved?
I don't see any reason to this, since not all the events are displayed.

**Comment by aldabil21** [comment]
This is an example of 200 events within 15 days https://codesandbox.io/s/186-wkprs3

It take ~2s in my case, but I guess this definitely could be improved

**Comment by naor10** [comment]
Hi,
After upgrading I cannot see all of the events on month view.

**Comment by aldabil21** [comment]
Right, not sure why I was looking into a hack rather than dig into the real issue.

Try the next release 2.7.12. Here a sandbox for 400 events per month https://codesandbox.io/s/186-wkprs3

Month view now seems more smooth than week/day views. I believe the week/day views also could benefits from similar enhancment, I will do that soon hopefully

**Comment by naor10** [comment]
Looking smooth now, thanks great job!
