### ISSUE TITLE
datePicker issue in 2.6.13 version

### ISSUE THREAD

**Issue by BansodeSahithiDeshmukh** [aldabil21/react-scheduler#199]
Hello @aldabil21, sorry for the delay of code sandbox, what i have observed is this issue is in the 2.6.13 version, here i have provided the codesanbox link : https://codesandbox.io/s/compassionate-night-7sim74?file=/src/App.tsx where on click of icon unable to see the datepicker.

where to test when i have upgraded the version, there datepicker visibilty and declaration on view is different i;e https://codesandbox.io/s/falling-pond-rngx5q

Thanks in advance.

_Originally posted by @BansodeSahithiDeshmukh in https://github.com/aldabil21/react-scheduler/issues/191#issuecomment-1530968752_

**Comment by aldabil21** [comment]
You are using incompatible versions, not how did you event install that.
1. First sandbox: v2.6.x require date picker v5. but you using v6. So thins will not work. Thats why its not working, if you check the console you will see the errors/warnings. To solve it, downgrade date-picker to v5.
2. Second is the correct picker. 

Again, we don't have a navigation picker with icon, this is due to incompatible versions you are using.

I strongly recommend you to use the latest version. ReadMe has multiple & example, please start from there.
