### ISSUE TITLE
Position of events wrong in my setup

### ISSUE THREAD

**Issue by appusvivek** [aldabil21/react-scheduler#271]
`    <Scheduler
      view="week"
      week={{
        step: 10
      }}
      events={[
        {
          event_id: 1,
          title: "Event 1",
          start: new Date("2023/10/30 09:30"),
          end: new Date("2023/10/30 10:30")
        },
        {
          event_id: 2,
          title: "Event 2",
          start: new Date("2023/10/30 11:00"),
          end: new Date("2023/10/30 11:30")
        }
      ]}
    />`
    
    Tried the same code in sandbox and my env both produce different results. Attaching screenshots as well. Please help me figure out.
    
    
![image](https://github.com/aldabil21/react-scheduler/assets/11013526/788b3f64-6cde-488d-a87f-99ea4a4f55fc)
<img width="1330" alt="image" src="https://github.com/aldabil21/react-scheduler/assets/11013526/f4335e57-650e-4648-aca9-4cf30ccd6f28">

**Comment by Memaree** [comment]
I also have this problem. The issue is severity scales with the height of the calender and the lower down the event is. If you go all the way to the bottom it ends up looking like this. I'm guessing this has to do with how it's getting the screen height or the container height.
top:
![image](https://github.com/aldabil21/react-scheduler/assets/121736715/33c9043c-6e65-430e-a076-0168730cd74c)

bottom:
![image](https://github.com/aldabil21/react-scheduler/assets/121736715/13168971-ec50-4188-be8a-2cb4ffd47066)

**Comment by GoodestUsername** [comment]
I also have this problem. The issue is severity scales with the height of the calender and the lower down the event is. If you go all the way to the bottom it ends up looking like this. I'm guessing this has to do with how it's getting the screen height or the container height.
top:
![image](https://github.com/aldabil21/react-scheduler/assets/121736715/33c9043c-6e65-430e-a076-0168730cd74c)

bottom:
![image](https://github.com/aldabil21/react-scheduler/assets/121736715/13168971-ec50-4188-be8a-2cb4ffd47066)

**Comment by aldabil21** [comment]
Please see https://github.com/aldabil21/react-scheduler/issues/197

Feel free to reopen if you think its not the same issue

**Comment by GoodestUsername** [comment]
> Please see #197
> 
> Feel free to reopen if you think its not the same issue

Doesn't seem to be?
![image](https://github.com/aldabil21/react-scheduler/assets/59536503/8dc9fe45-745f-4823-b6a7-ddf2b6bb9198)

![image](https://github.com/aldabil21/react-scheduler/assets/59536503/72b0249b-f9e1-4e48-8501-b2ed65d152c4)
