### ISSUE TITLE
Events overlap in month view (but not in week view)

### ISSUE THREAD

**Issue by alantygel** [aldabil21/react-scheduler#273]
Hi,

Thanks for the awesome component! Really amazing.

I've noticed that in month view, events always render at the first line, even if there are other multiday events on the same line. When there are a lot of events, this turns difficult to distinguish which are the events happening on that day. I'm curious if this was designed so, because in week view this doesn't happen.

In the example bellow, events starting at the 15th and 16th overlap the previous event in month view, but not in week view:

Month view:
![image](https://github.com/aldabil21/react-scheduler/assets/1626935/b6bdc171-9d41-4549-9766-e04d3375e9fa)

Week view:
![image](https://github.com/aldabil21/react-scheduler/assets/1626935/28ecbaf9-c525-4610-93cc-c0c55d8e27e8)

Is there any prop to control this behaviour?

best,
alan

**Comment by vanyadymousky** [comment]
<img width="915" alt="Screenshot 2023-12-05 at 11 26 10 PM" src="https://github.com/aldabil21/react-scheduler/assets/922747/b470122d-f689-4c28-9856-46cddd00c48d">
Hello, the same question: have overlapping, but in a week view. Events overlap by day that causes them joining into single event row instead of a new line. Customise event render doesn't work for all day events. What else may I try to avoid this issue?
