### ISSUE TITLE
Day-view event overflows from the header

### ISSUE THREAD

**Issue by NiharR27** [aldabil21/react-scheduler#29]
Hi there, I am using the react-scheduler, it is working perfectly for week and month (the events) are appearing perfectly inside the given cell. But it seem to be not the same case for the day event.

Here is the month view (it is good):
<img width="874" alt="Screen Shot 2022-06-24 at 10 25 23 pm" src="https://user-images.githubusercontent.com/52943748/175534390-5a627730-7fe2-4507-bd99-b0994f031f25.png">

Here is the day view:
<img width="874" alt="Screen Shot 2022-06-24 at 10 25 57 pm" src="https://user-images.githubusercontent.com/52943748/175534701-831dca98-7508-46bb-a604-aa949250f20f.png">

Note: it goes into the header (it is supposed to start at 8AM) (where it says today's date).

I am using resource headers etc, but I am not any other exteral styles which could cause this.

Although passing this day configs

` day={{
            startHour: 8,
            endHour: 23,
            step: 30,
            cellRenderer: cellOverride,
          }}`

Cell override being: 
`const CellOverride = styled('div')<CellRenderedProps>(({ height }) => ({
  width: '100%',
  height,
  margin: 0,
  border: 0,
  background: 'transparent',
}));`

Tried commenting these codes out and just passed the events and it still seemed to calculate the wrong position.

Would there be anything that we need to consider for the start height of the component?

**Comment by NiharR27** [comment]
@aldabil21  - little help here please :)

**Comment by NiharR27** [comment]
Also tried here from the examples: 
[](https://codesandbox.io/s/b2kbv)

Tried creating an event at 8AM in this example, it overflows there too...

<img width="1447" alt="Screen Shot 2022-06-24 at 10 38 39 pm" src="https://user-images.githubusercontent.com/52943748/175537531-3fdbe74d-0f74-4bda-ad08-53ade33bba3c.png">

**Comment by aldabil21** [comment]
Hi @NiharR27 

Yes you are right, if your calendar table `startHour` is from _9am_, and then you create an event at _8am_, this would overflow above the calendar and evantually fade out of grid if was _7am_ for example. 
![Screenshot from 2022-06-24 16-07-37](https://user-images.githubusercontent.com/58398437/175543576-e65e1ce6-65e4-4db8-adce-2d9df00fe546.png)



I think I haven't make this case into consideration, cuz if you have a _9am_ to _11pm_ calendar as of your example, then events should be validated before confirming/saving, and since it's _8am_ event, then it should not be added, perhaps you could auto-fix time-slot, or return error that it's not within time-frame. 

So I think your solution is to override the `onConfirm` method and validate the time to be consistant with your calendar `startHour` and `endHour`.

Hope this helps

And this is a good issue, it should be solved in someway.

**Comment by aldabil21** [comment]
Known that this issue is in day-view & week-view as well, since both views align events with the exact hour/minutes rows.

**Comment by NiharR27** [comment]
Thanks @aldabil21 - I think that i mis-wrote in the pictures...

So, for the first picture (my start hour is at 8 and end is 23), i created an event at 8 and it overflows from the top...


In the second code sand box example with this link ->  https://codesandbox.io/s/b2kbv

There the start time is 9AM and i created an event on 9AM by clicking the cell and creating and when it refreshed the calendar, it still overflowed there.

Would there be any reason why?

**Comment by aldabil21** [comment]
Good job @NiharR27 
That was a bug in the day-view starting hour.

Can you check the same Sandbox you had issue with -> https://codesandbox.io/s/b2kbv  and let me if it works for you.

If so, then upgrade to v2.2.2

**Comment by NiharR27** [comment]
@aldabil21  - Thanks :), i will try it on Monday and let you know. we can close this issue and can reopen later if the issue persists if you'd like :) Thanks again.
