### ISSUE TITLE
custom component for month view cell

### ISSUE THREAD

**Issue by KirillSuhodolov** [aldabil21/react-scheduler#314]
Hi, @aldabil21 
thanks for library 

is it possible to add component that replace default component for month view for cell with events?
as eventRenderer function don't work for month view, may be something like eventsRenderer?

**Comment by aldabil21** [comment]
Hi

This is intertional and it's mentioned here if you would like to refrence the code https://github.com/aldabil21/react-scheduler/blob/e446ab08ba5a6a51dd17fd40e5a3758263028f5c/src/lib/components/events/EventItem.tsx#L57

The issue is in multi-day events & month view that it is so hard to make it custom, I have to conditionally render the arrows, width, and max number of available events accross days. Opening the customization for this will be easy to make mistakes.

Maybe you just want to customize the title, or color? Can you give me a visual example of how you would want to render a month event item? Maybe I can provide better help with this

**Comment by RosenTomov** [comment]
Sorry to hijack the thread, here is an example:
- Different events to have different styles depending on passed properties

I can extend the `ProcessedEvent` and pass my own props, but I can't change the component.

Maybe an easier and safer way would be to at least add `sx` to the monthly view event, prop can be  `sx?: SxProps<Theme> | undefined;`

And in the `<Scheduler />` , we can pass a fn.
```
monthlyEventStyle={({event}) =>
// logic here, changing styles depending on `event` data
return { background:"x", border:"y", etc. }
}
```
