### ISSUE TITLE
Support for date-fns v3

### ISSUE THREAD

**Issue by kraffi83** [aldabil21/react-scheduler#347]
Hello everyone,
When will date-fns v3 be supported?
Best regards

**Comment by slash-84** [comment]
@aldabil21 what about making the lib agnostic from the adapter?

Since the lib heavily rely on `mui` we can try to use the same approach of Pickers and ask the developer to wrap on the preferred LocalizationProvider.

I understand it's a big change, I imagine al the `format` and date calculation functions should be revised under the same common interface used by mui.

**Comment by aldabil21** [comment]
@slash-84  The breaking changes for v3 are the import strategy, no more default imports.
This component already uses named imports, so the changes needed to upgrade is just the adapter.

If its possible to not force the upgrade and can make it optional, I think would be awesome. Can you check #349 and adjust it to support the idea you mentioned?

**Comment by slash-84** [comment]
I should investigate a bit more. At the moment is just a raw idea, we should do some experiment. For sure it will be a big change:

- not using `LocalizationProvider` inside the lib, but ask the developer to wrap it with the chosen one, like `mui` ask developers to wrap Pickers
- not using date-fns at all and try to rely on the hook `useLocalizationContext()` in `@mui/x-date-pickers/internals`. It should have the necessary (🤞) to handle dates using an abstraction of the chosen date library.

In this way react-scheduler could become agnostic from both the locale and date adapted, giving the developer the possibility to chose from the ones offered by `mui`
