### ISSUE TITLE
daylight savings time: wrong event positioning after update

### ISSUE THREAD

**Issue by slash-84** [aldabil21/react-scheduler#350]
In countries that make use of daylight savings time there is a strange behaviour when moving events around the legal time change.

Steps to reproduce:

https://codesandbox.io/p/sandbox/standard-forked-3tj9r3

Try to move (drag & drop, or edit modal) "Event 1" from Sat 30 03:00 - 04:00 to Sun 31 03:00 - 04:00.

The new event will be placed on the previous cell (02:00 - 03:00).

Also Event 2 is reporting correct dates, but wrong position.

Tested with Italy's daylight savings (31/03/2024 at 02:00 AM).

**Comment by aldabil21** [comment]
Thx for pointing this out

1. For the issue related to the exact hour switching from summary/standard time, I havent find a proper way to fix it. I can see it also in other calendar packages. For example [in this react big calendar](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/examples--example-2&globals=backgrounds.grid:false;backgrounds.value:transparent) you cannot add an event from **1-2 AM 31/3/2024**. It has to be 1-3 and more. Basiaclly there is **no 2AM in that day**.
2. In the day where summer/standard switch occur, there is kinda of missing 1h, which makes the event placed on previous cell. This is a bug, and should be fixed in #352
