### ISSUE TITLE
disable edit and delete

### ISSUE THREAD

**Issue by paweenacho** [aldabil21/react-scheduler#36]
I can disable icon edit and delete ?  I can disable something role

**Comment by aldabil21** [comment]
Unfortunately, you cannot do that directly or explicitly. This component made to be specifically a scheduler rather than a calendar.

However, here some ways you can controll the edit/delete functionality:
1. You can add `disabled: true` to the event object, this way the show event component popup will not show at all.
2. Override the `onDelete` function and allow/disallow delete.
3. Override the `customEditor` function and allow/disallow edit.

Hope that helps. If you still have an issue you can re-open.
