### ISSUE TITLE
Event IDs cannot be 0

### ISSUE THREAD

**Issue by adamboduch** [aldabil21/react-scheduler#44]
I think there's some check for a "falsey" value happening with `event_id` somewhere because I cannot use `0` as an event ID. When I do, the `scheduler.edited` value is null when I try to use a `customEditor` function. Let me know if you need me to clarify anything.

**Comment by aldabil21** [comment]
You are right. also, you will not be able to delete it.

and that's because it's been designed like: if no event_id, then no event, then it's an empty space/grid, so set the selected range and put the editor in "add" mode, instead of "edit" mode.

Specifically this case:
https://github.com/aldabil21/react-scheduler/blob/c79e123d82154f10b5065ea45ee284414954311f/src/lib/context/state/stateReducer.ts#L24

I think I made it like this cus I re-used the same function for add & edit. If you are forced to use a "falsy" number like 0, will it work for you to make it a `string`? It will work with Typescript since event_id is defined `number | string`.

Otherwise, I think can find a solution for it, or PRs are welcome if you would like to handle it.

**Comment by aldabil21** [comment]
Umm, I just ran some tests. I would rather not to change this.

ids are meant to be truthy and unique, sort of keys, I can't think of a case where id/key would be something falsy for any storage or database.

So I think the better solution is to try to fix your Ids.

Cheers

**Comment by adamboduch** [comment]
I have a work-around for this, so no worries. The only reason I found the issue is because the events that I want to render don't have IDs, so I used the index of the event as the ID.
