### ISSUE TITLE
No way to refresh remote events

### ISSUE THREAD

**Issue by adamboduch** [aldabil21/react-scheduler#45]
It seems like if I'm only using remote data, there's no way to refresh it? For example, the only way to add or remote new events is by using the `onConfirm` or `onDelete` props to return the edited/created or deleted event respectively. With the APIs I have, this is not possible, all I can do is refresh the list of events. I've tried this using `events` and `remoteEvents` to no avail. If I could just somehow call [this function](https://github.com/aldabil21/react-scheduler/blob/master/src/lib/views/Week.tsx#L77) after I create/edit/delete, I'd be all set.

Any guidance much appreciated.

**Comment by aldabil21** [comment]
Hi @adamboduch 

I think you can go the easy way, since as far as I understood, your end-point have the events without ids, I'm not sure how you can delete event, and get event by id. So I only made some assumptions with a solution in this [sandbox](https://codesandbox.io/s/remote-data-not-returning-gfc0i4)

If you could put up an example sandbox maybe I can give a better help. Let me know

**Comment by aldabil21** [comment]
Reopen if u still have issue
