### ISSUE TITLE
Feature Request - Customized actions on cell selection

### ISSUE THREAD

**Issue by RLangridge** [aldabil21/react-scheduler#5]
Hi there,

I attempted to fork your repo (https://github.com/RLangridge/react-scheduler) and add this in myself but I've run into nightmares in terms of packing so I thought I'd ask here. Is there any chance you could add the ability to inject custom code when a user selects an empty cell and an event? I want to be able to show a custom view when my users select an event cell and perform custom actions within that view. I also want to make the empty cells read-only, so that they can't be added too. My apologies if this functionality already exists and I just couldn't find it.

Thanks!

**Comment by aldabil21** [comment]
Hi @RLangridge 

I've looked into your fork to get an idea what you like to do. While these options are not internally exists, you can intercept the default behaviour and make it happen by using `customEditor` & `viewerExtraComponent`.

Look into this [exmple sandbox](https://codesandbox.io/s/custom-actions-n02dv) and let me know if the idea is there. It's not arranged well, you can do better spliting componenets and make it better.

>  I want to be able to show a custom view when my users select an event cell and perform custom actions within that view

Let me know if the example solve it for you.

> I also want to make the empty cells read-only

You may find warning about *unable to change state for unmounted component* because we are closing the editor then have to return something. If you don't care about it in the meanwhile, let me know if it works for you.

Hope this helps

**Comment by RLangridge** [comment]
Hi @aldabil21 

Thank you so much for the example you've posted. I think I should be able to use this for our project. I just have one more question: Is it possible to only show only a date range? Our client wants to be able to show just the current day and the next day (Is it currently possible to intercept the date header that lets you pick "Day, Week, Month")?

Thanks so much for your time

**Comment by aldabil21** [comment]
You welcome.

I think there will some limitation on this, you can limit the view to "only today and tomorrow", and remove the "month, weel, day" views. But the user will still be able to navigate using the top left calendar and arrows. There is no controls of that from options/props.

I've updated the same example, check it out and let me know if it may work for you.

**Comment by RLangridge** [comment]
Thanks for looking into this. Unfortunately I need a way to possibly even just disable those arrow buttons and have it in the day view. I might make a fork later and try to implement it myself and ask for a PR (This isn't an urgent requirement from our client thankfully).

Thank you for your time.

**Comment by aldabil21** [comment]
PR are welcome.
