### ISSUE TITLE
Possible to have a customEventItem?

### ISSUE THREAD

**Issue by asumpter** [aldabil21/react-scheduler#55]
I like your project so far and it works really well. I see we can pass custom title and extra components into for when the popper is open, is it possible to add customEventItem so the user has control over how it looks on the scheduler?

**Comment by aldabil21** [comment]
Hi
Since this component is opinionated and totally depends on MUI, so the event item is intentionally been designed with the look & feel of MUI.

However, the event item is just a `paper` component, I believe you can target it and style it with your theme setup, though it would change all event items and not cherry-picked items, if you share a sandbox and try to tell me what you want to achieve, I might give a better help.

btw: if you just want to change the background, you can pass `color: string` to the event item object and it will be applied, I think this is not mentioned in the ReadMe.

**Comment by asumpter** [comment]
I use MUI so don't mind the opinionated look. I was thinking it would be nice to show additional data points on scheduler like this example. Where you have the title, time, and then a location at the bottom in this screenshot. It seems the EventItem is limited to just title and time.

![Screen Shot 2022-10-19 at 1 09 40 PM](https://user-images.githubusercontent.com/84922782/196795456-e6fa77bd-6182-4ab5-ae68-5ae0f93f0d2c.png)

**Comment by aldabil21** [comment]
I believe you can accomplish that if you update to v2.5.1
See sandbox example: https://codesandbox.io/s/custom-event-renderer-rkf4xw

Known that it's not applicable to month view, or multi-day events, It will mostly be broken if you apply it to these cases, since an event height is barely have enough height in those cases.

Hope this helps

**Comment by asumpter** [comment]
Great! Thanks for the quick turn around, I'll take a look.
