### ISSUE TITLE
Responsive modal at mobile

### ISSUE THREAD

**Issue by Sitaras** [aldabil21/react-scheduler#63]
![image](https://user-images.githubusercontent.com/45051550/199926681-495ffa77-28f9-4ca2-93e3-2ac21b79652d.png)

I think that the modal isn't responsive at mobile, it cover all the screen, as you can see.

**Comment by aldabil21** [comment]
By design, the modal will take the fullscreen in mobile, which arguably is a better experience for mobile
https://github.com/aldabil21/react-scheduler/blob/4a498ce4dd3534456d2ef044740d54b1af86f556/src/lib/views/Editor.tsx#L230

Since you are using a custom editor, you are in charge of arranging the modal fields and buttons. You could make it better though, here is an example with the same fields you are using.

![Screenshot from 2022-11-04 11-49-14](https://user-images.githubusercontent.com/58398437/199931775-5b7529c6-540a-41cb-8121-1d4840791549.png)
